# Generated by Django 3.1.6 on 2021-02-22 09:37

from django.db import migrations, models
import django.db.models.deletion
import eshop_products.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0002_product_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Image_Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(null=True, upload_to=eshop_products.models.file_upload_gallery_image)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop_products.product')),
            ],
        ),
    ]
