# Generated by Django 3.1.6 on 2021-02-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0003_product_image_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visit',
            field=models.IntegerField(default=0),
        ),
    ]
