# Generated by Django 3.1.6 on 2021-02-27 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0006_auto_20210227_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date_created',
            new_name='dateTime',
        ),
    ]
