# Generated by Django 3.1.6 on 2021-02-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0007_auto_20210227_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='visit',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
