# Generated by Django 3.1.6 on 2021-02-21 23:59

from django.db import migrations, models
import eshop_slider.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_slider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='image',
            field=models.ImageField(null=True, upload_to=eshop_slider.models.file_upload_name),
        ),
    ]
