# Generated by Django 3.1.6 on 2021-02-27 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0008_auto_20210227_1813'),
        ('eshop_slider', '0003_slider_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eshop_products.product'),
        ),
    ]
