# Generated by Django 3.1.6 on 2021-02-23 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact Forms'},
        ),
    ]
