# Generated by Django 3.1.6 on 2021-02-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_order', '0003_auto_20210224_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='owner_id',
            field=models.IntegerField(null=True),
        ),
    ]
